name: Wake Render App

on:
  schedule:
    - cron: '30 19 * * 1' # Every Monday at 7:30 PM UTC (10:30 PM Nairobi)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render app root
        run: curl -s -o /dev/null -w "%{http_code}" https://carwashwaterbilltracking-backend.onrender.com/
